[package]
authors.workspace = true
categories = []
default-run = "template-rs-api"
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["app", "binary", "clap", "cli", "template"]
license.workspace = true
name = "template-rs-api"
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
bench = true
name = "template-rs-api"
path = "src/main.rs"
test = true

[build-dependencies]

[dependencies]
# Custom crates
decanter = { features = ["derive"], version = "0.1.5" }

# Standard dependencies
anyhow = "1"
async-trait = "0.1"
axum = { features = ["headers", "http2", "macros"], version = "0.6" }
axum-core = "0.3"
chrono = "0.4"
clap = { features = ["cargo", "derive", "env"], version = "4" }
config = "0.13"
futures = "0.3.25"
glob = "0.3"
http = "0.2.8"
hyper = { features = [], version = "0.14" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
smart-default = "0.7"
strum = { features = ["derive"], version = "0.24" }
tokio = { features = ["full"], version = "1" }
tower = "0.4"
tower-http = { features = ["full"], version = "0.4" }
tracing = "0.1"
tracing-subscriber = { features = ["env-filter"], version = "0.3" }

[dev-dependencies]

