name: Docker

on:
  pull_request:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

env:
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: [ latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build --tag ${{ env.DOCKERHUB_USERNAME }}/template-bin-rs:${{ matrix.tags }} .
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        dockerfile: Dockerfile
        name: ${{ env.DOCKERHUB_USERNAME }}/template-bin-rs
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        snapshot: true
        username: ${{ env.DOCKERHUB_USERNAME }}
