name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --release -v --workspace
      - run: cargo test --all --all-features -v --release
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (conduit)
        run: cargo publish --all-features -v -p conduit --token ${{ secrets.CARGO_REGISTRY_TOKEN }}