name: Vault

on:
  pull_request:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          namespace: admin
          token: ${{ secrets.VAULT_TOKEN }}
          url: ${{ secrets.VAULT_URL }}
          secrets: |
              secret/cargo cargo_registry_token ;
